#ifndef RTC_CONFIG_H
#define RTC_CONFIG_H

#ifndef RTC_ENABLE_TURN
#define RTC_ENABLE_TURN 0
#endif

#ifndef RTC_ENABLE_STATS
#define RTC_ENABLE_STATS 0
#endif

#ifndef RTC_WITH_MBEDTLS
#define RTC_WITH_MBEDTLS 0
#endif

#ifndef RTC_WITH_USRSCTP
#define RTC_WITH_USRSCTP 0
#endif

#ifndef RTC_DEFAULT_MEMPOOL_BYTES
#define RTC_DEFAULT_MEMPOOL_BYTES (512 * 1024)
#endif

#ifndef RTC_DEFAULT_MAX_CHANNELS
#define RTC_DEFAULT_MAX_CHANNELS 8
#endif

#ifndef RTC_DEFAULT_MAX_MESSAGE_SIZE
#define RTC_DEFAULT_MAX_MESSAGE_SIZE 1200
#endif

#endif
