#ifndef RTC_CONFIG_H_
#define RTC_CONFIG_H_

#include <stdint.h>

#ifndef RTC_CFG_DEFAULT_ACTIVE_PEERS
#define RTC_CFG_DEFAULT_ACTIVE_PEERS 1u
#endif

#ifndef RTC_CFG_MAX_PEERS
#define RTC_CFG_MAX_PEERS 2u
#endif

#ifndef RTC_CFG_MAX_LOCAL_CANDIDATES
#define RTC_CFG_MAX_LOCAL_CANDIDATES 8u
#endif

#ifndef RTC_CFG_MAX_REMOTE_CANDIDATES
#define RTC_CFG_MAX_REMOTE_CANDIDATES 8u
#endif

#ifndef RTC_CFG_MAX_CANDIDATE_PAIRS
#define RTC_CFG_MAX_CANDIDATE_PAIRS 16u
#endif

#ifndef RTC_CFG_RTP_RX_QUEUE
#define RTC_CFG_RTP_RX_QUEUE 16u
#endif

#ifndef RTC_CFG_RTCP_FB_QUEUE
#define RTC_CFG_RTCP_FB_QUEUE 8u
#endif

#ifndef RTC_CFG_RTX_CACHE
#define RTC_CFG_RTX_CACHE 32u
#endif

#ifndef RTC_CFG_MTU
#define RTC_CFG_MTU 1200u
#endif

#ifndef RTC_CFG_MAX_SDP_LEN
#define RTC_CFG_MAX_SDP_LEN 2048u
#endif

#ifndef RTC_CFG_MAX_CANDIDATE_LEN
#define RTC_CFG_MAX_CANDIDATE_LEN 256u
#endif

#ifndef RTC_CFG_ENABLE_INTERNAL_WORKER
#define RTC_CFG_ENABLE_INTERNAL_WORKER 0
#endif

#ifndef RTC_CFG_ICE_CONNECT_TICKS
#define RTC_CFG_ICE_CONNECT_TICKS 2u
#endif

#ifndef RTC_CFG_DTLS_CONNECT_TICKS
#define RTC_CFG_DTLS_CONNECT_TICKS 2u
#endif

#ifndef RTC_CFG_DTLS_HANDSHAKE_TIMEOUT_MS
#define RTC_CFG_DTLS_HANDSHAKE_TIMEOUT_MS 3000u
#endif

#ifndef RTC_CFG_DTLS_MAX_DATAGRAM
#define RTC_CFG_DTLS_MAX_DATAGRAM 1600u
#endif

#ifndef RTC_CFG_DTLS_MAILBOX_CAP
#define RTC_CFG_DTLS_MAILBOX_CAP 8u
#endif

#ifndef RTC_CFG_SRTP_MAX_TRAILER
#define RTC_CFG_SRTP_MAX_TRAILER 16u
#endif

#define RTC_CFG_RTP_HEADER_LEN 12u
#define RTC_CFG_MAX_MEDIA_PAYLOAD ((uint16_t)(RTC_CFG_MTU - RTC_CFG_RTP_HEADER_LEN))

#if RTC_CFG_DEFAULT_ACTIVE_PEERS == 0
#error "RTC_CFG_DEFAULT_ACTIVE_PEERS must be >= 1"
#endif

#if RTC_CFG_DEFAULT_ACTIVE_PEERS > RTC_CFG_MAX_PEERS
#error "RTC_CFG_DEFAULT_ACTIVE_PEERS must be <= RTC_CFG_MAX_PEERS"
#endif

#if RTC_CFG_MAX_PEERS == 0
#error "RTC_CFG_MAX_PEERS must be >= 1"
#endif

#if RTC_CFG_MAX_CANDIDATE_PAIRS < RTC_CFG_MAX_LOCAL_CANDIDATES
#error "RTC_CFG_MAX_CANDIDATE_PAIRS should be >= RTC_CFG_MAX_LOCAL_CANDIDATES"
#endif

#endif  // RTC_CONFIG_H_
