#ifndef RTC_STATUS_H
#define RTC_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum rtc_status_t {
    RTC_STATUS_OK = 0,
    RTC_STATUS_INVALID_ARGUMENT,
    RTC_STATUS_INVALID_STATE,
    RTC_STATUS_UNSUPPORTED,
    RTC_STATUS_CAPACITY,
    RTC_STATUS_CAPACITY_ARENA,
    RTC_STATUS_CAPACITY_SDP_BUFFER,
    RTC_STATUS_CAPACITY_ICE_CANDIDATES,
    RTC_STATUS_CAPACITY_TIMER_SLOTS,
    RTC_STATUS_CAPACITY_PACKET_CACHE,
    RTC_STATUS_CAPACITY_TRACE_BUFFER,
    RTC_STATUS_AFFINITY_VIOLATION,
    RTC_STATUS_PROTOCOL_ERROR,
    RTC_STATUS_BACKEND_ERROR
} rtc_status_t;

#ifdef __cplusplus
}
#endif

#endif
