find_package(OpenSSL QUIET)

find_path(RTC_OPTIONAL_SECURITY_LIBSRTP_INCLUDE_DIR
    NAMES srtp2/srtp.h
)

find_library(RTC_OPTIONAL_SECURITY_LIBSRTP_LIBRARY
    NAMES srtp2 srtp
)

if(NOT OpenSSL_FOUND OR NOT RTC_OPTIONAL_SECURITY_LIBSRTP_INCLUDE_DIR OR NOT RTC_OPTIONAL_SECURITY_LIBSRTP_LIBRARY)
    message(FATAL_ERROR
        "Install optional Chrome E2E security dependencies or configure with "
        "-DRTC_CHROME_E2E_WITH_OPTIONAL_SECURITY=OFF")
endif()

set(RTC_OPTIONAL_SECURITY_INCLUDE_DIRS
    ${OPENSSL_INCLUDE_DIR}
    ${RTC_OPTIONAL_SECURITY_LIBSRTP_INCLUDE_DIR}
)

set(RTC_OPTIONAL_SECURITY_LIBRARIES
    OpenSSL::SSL
    OpenSSL::Crypto
    ${RTC_OPTIONAL_SECURITY_LIBSRTP_LIBRARY}
)

message(STATUS "Chrome E2E optional security deps: OpenSSL=${OPENSSL_VERSION}, libsrtp=${RTC_OPTIONAL_SECURITY_LIBSRTP_LIBRARY}")
